name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document to dvi
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
          compiler: uplatex
      - name: Compile dvi to pdf
        uses: dante-ev/latex-action@master
        with:
          root_file: main.dvi
          compiler: dvipdfmx
