name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: make LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: all
          compiler: make
          args: ""
          extra_system_packages: make
      - name: Upload output pdf
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: main.pdf
